services:
    pe_user.controller.reset_password:
        public: true
        class: PE\Bundle\UserBundle\Controller\ResetPasswordController

    pe_user.message.reset_password:
        public: true
        class: PE\Bundle\UserBundle\Message\Message
        arguments:
            - '%pe_user.message_transports%'
            - '%pe_user.message.reset_password%'