PE\Bundle\UserBundle\Model\User:
    type: mappedSuperclass
    fields:
        token:
            type: string
            nullable: true
        username:
            type: string
        email:
            type: string
        phone:
            type: string
        roles:
            type: collection
        password:
            type: string
        salt:
            type: string
            nullable: true