pe_user__registration_confirmed:
    path: /confirmed/
    methods: [GET]
    defaults:
        _controller: pe_user.controller.registration:confirmedAction

pe_user__registration_confirm:
    path: /confirm/{token}/
    methods: [GET, POST]
    defaults:
        _controller: pe_user.controller.registration:confirmAction

pe_user__registration_registered:
    path: /registered/
    methods: [GET, POST]
    defaults:
        _controller: pe_user.controller.registration:registeredAction

pe_user__registration_register:
    path: /
    methods: [GET, POST]
    defaults:
        _controller: pe_user.controller.registration:registerAction