pe_user__reset_password_reset:
    path: /reset/{token}
    methods: [GET, POST]
    defaults:
        _controller: pe_user.controller.reset_password:resetAction

pe_user__reset_password_requested:
    path: /requested/
    methods: [GET, POST]
    defaults:
        _controller: pe_user.controller.reset_password:requestedAction

pe_user__reset_password_request:
    path: /
    methods: [GET, POST]
    defaults:
        _controller: pe_user.controller.reset_password:requestAction

